### ISSUE TITLE
Gün sonunda çıkan hata

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#166]
30/06/2017 tarihinde gün sonunda aşağıdaki hatayı alıyoruz. 

_08:30:09 ------------------------------
08:30:09         VOBALGO V0.5.7g
08:30:09 ------------------------------
08:30:09 
18:15:15 Settings.Load()
18:15:15 The process cannot access the file 'D:\EN\PERSONAL STAFF\1. VOB ALGO\Program\V0.5.7\VOB ALGO\settings.xml' because it is being used by another process.
18:15:15    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at VOB_ALGO.Engine.Settings.Load()_

**Comment by boratuncer** [comment]
Log'un biraz daha geniş hali var mı ?

**Comment by boratuncer** [comment]
Problem çözüldü.

**Comment by boratuncer** [comment]
V0.5.8a da devam ediyor mu ?
