### ISSUE TITLE
Log Alırken Programın Hata Vermesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#170]
Error dosyasındaki hatayı aşağıda bulabilirsin.

08:26:37 ------------------------------
08:26:37         BOXER : V0.5.7h
08:26:37 ------------------------------
08:26:37 
13:02:38 Settings.Load()
13:02:38 The process cannot access the file 'D:\EN\PERSONAL STAFF\1. VOB ALGO\Program\V0.5.7\VOB ALGO\settings.xml' because it is being used by another process.
13:02:38    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at VOB_ALGO.Engine.Settings.Load()
13:10:01 ------------------------------
13:10:01         BOXER : V0.5.7h
13:10:01 ------------------------------
13:10:01

**Comment by boratuncer** [comment]
Log alırken değil, settings dosyasını okurken problem ile kaşılaşmış, 13:02 öncesinde hangi işlemler yapıldı ?

Yapılan işlemlerden biri settings dosyasına erişiyor ve bırakmıyor.

**Comment by erkannurel** [comment]
Log aldığım bir programda yaptığım bir işlem yok. Benim müdahalem olmadan programın kendisi settings dosyasına erişip bırakmıyor olabilir mi?

**Comment by boratuncer** [comment]
#166 nolu bug ile aynı, o bug üzerinden takip edilecek
