### ISSUE TITLE
Log Alırken Programın Hata Vermesi 2

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#172]
08:45:23 ------------------------------
08:45:23         BOXER : V0.5.7j
08:45:23 ------------------------------
08:45:23 
08:46:04 ------------------------------
08:46:04         BOXER : V0.5.7j
08:46:04 ------------------------------
08:46:04 
18:16:12 Settings.Load()
18:16:12 The process cannot access the file 'D:\EN\PERSONAL STAFF\1. VOB ALGO\Program\V0.5.7\VOB ALGO\settings.xml' because it is being used by another process.
18:16:12    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at VOB_ALGO.Engine.Settings.Load()

**Comment by boratuncer** [comment]
#166 nolu bug ile aynı, o bug üzerinden takip edilecek
