### ISSUE TITLE
DateTime parse hatası

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#183]
21:26:08 batchProcesVIHLForTPSL
21:26:08 String was not recognized as a valid DateTime.
21:26:08    at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value)
   at VOBALGO.Engine.DataLists.Add(DataItem item) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\DataLists.cs:line 870
   at VOB_ALGO.Engine.BatchProcess.BatchProcessVILHFast(String contractName, algoVihl algo, SignalConfig signalConf, List`1 dataItem) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\BatchProcess.cs:line 172
   at VOB_ALGO.Engine.BatchProcess.VIHLForTPSL(String fileName, algoVihl algo, BatchVIHL param, SignalConfig signalConf, String contractName) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\BatchProcess.cs:line 604

**Comment by boratuncer** [comment]
Problem çözüldü.
