### ISSUE TITLE
Canlı veri akışı problemi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#228]
Application: VOB ALGO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   at VOBALGO.Engine.DataLists.getLastEnDataItem()
   at VOB_ALGO.MainForm.ddeProcessAdvise(VOB_ALGO.Engine.DdeData)
   at VOB_ALGO.MainForm.ddeClientAdvise(System.Object, NDde.Client.DdeAdviseEventArgs)
   at NDde.Client.DdeClient.OnAdviseReceived(System.Object, NDde.Foundation.Client.DdemlAdviseEventArgs)
   at NDde.Foundation.Client.DdemlClient+AdviseLoop.Process(Int32, Int32, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
   at NDde.Foundation.Client.DdemlClient.ProcessCallback(NDde.Foundation.Advanced.DdemlTransaction)
   at NDde.Foundation.Advanced.DdemlContext.OnDdeCallback(Int32, Int32, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageA(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at VOB_ALGO.Program.Main()

**Comment by boratuncer** [comment]
Problem çözüldü
