### ISSUE TITLE
DDEWrapper sınıfına yeni hata kodu eklenmesi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#304]
DDEWrapper sınıfına yeni hata kodu eklenecek

08:15:29 DDEWrapper.initDDE()
08:15:29 The client failed to connect to "MTX|DATA".  Make sure the server application is running and that it supports the specified service name and topic name pair.
08:15:29 NDde.Foundation.DdemlException: The client failed to connect to "MTX|DATA".  Make sure the server application is running and that it supports the specified service name and topic name pair.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at NDde.Advanced.DdeContext.DdeThread.Invoke(Delegate method, Object[] args)
   at NDde.Client.DdeClient.Connect()

**Comment by boratuncer** [comment]
İlgili hata kodu eklendi.
